In [1]:
from utils import *

In [2]:
train_df_orig = load_dataset('local', 'train.tsv')
train_df = train_df_orig

test_df_orig = load_dataset('local', 'test.tsv')
test_df = test_df_orig

# test2_df_orig = load_dataset('local', 'test_stg2.tsv')
# test2_df = test2_df_orig

In [3]:
train_df

,name,item_condition_id,category_name,brand_name,price,shipping,item_description
train_id,,,,,,,
0,MLB Cincinnati Reds T Shirt Size XL,3,Men/Tops/T-shirts,NaN,10.0,1,No description yet
1,Razer BlackWidow Chroma Keyboard,3,Electronics/Computers & Tablets/Components & P...,Razer,52.0,0,This keyboard is in great condition and works ...
2,AVA-VIV Blouse,1,Women/Tops & Blouses/Blouse,Target,10.0,1,Adorable top with a hint of lace and a key hol...
3,Leather Horse Statues,1,Home/Home Décor/Home Décor Accents,NaN,35.0,1,New with tags. Leather horses. Retail for [rm]...
4,24K GOLD plated rose,1,Women/Jewelry/Necklaces,NaN,44.0,0,Complete with certificate of authenticity
...,...,...,...,...,...,...,...
1482530,Free People Inspired Dress,2,Women/Dresses/Mid-Calf,Free People,20.0,1,"Lace, says size small but fits medium perfectl..."
1482531,Little mermaid handmade dress,2,Kids/Girls 2T-5T/Dresses,Disney,14.0,0,Little mermaid handmade dress never worn size 2t
1482532,21 day fix containers and eating plan,2,Sports & Outdoors/Exercise/Fitness accessories,NaN,12.0,0,"Used once or twice, still in great shape."
1482533,World markets lanterns,3,Home/Home Décor/Home Décor Accents,NaN,45.0,1,There is 2 of each one that you see! So 2 red ...
1482534,Brand new lux de ville wallet,1,Women/Women's Accessories/Wallets,NaN,22.0,0,"New with tag, red with sparkle. Firm price, no..."

In [4]:
train_df = preprocess(train_df)
X_train, y_train = extract_from_trainset(train_df)

In [5]:
X_train

,name,item_condition_id,shipping,item_description,has_brand,cat_Cosmetics and Body Care,cat_Digital Services,cat_Electronics,cat_Fashion,cat_Food and Beverage,cat_Furniture and Decor,cat_Health and Wellness,cat_Household Items,cat_Media,cat_Office Equipment,cat_Pet Care,cat_Toys and Hobbies
train_id,,,,,,,,,,,,,,,,,
0,MLB Cincinnati Reds T Shirt Size XL,3,1,No description yet,0,0,0,0,1,0,0,0,0,0,0,0,0
1,Razer BlackWidow Chroma Keyboard,3,0,This keyboard is in great condition and works ...,1,0,0,1,0,0,0,0,0,0,0,0,0
2,AVA-VIV Blouse,1,1,Adorable top with a hint of lace and a key hol...,1,0,0,0,1,0,0,0,0,0,0,0,0
3,Leather Horse Statues,1,1,New with tags. Leather horses. Retail for [rm]...,0,0,0,0,0,0,1,0,0,0,0,0,0
4,24K GOLD plated rose,1,0,Complete with certificate of authenticity,0,0,0,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1482530,Free People Inspired Dress,2,1,"Lace, says size small but fits medium perfectl...",1,0,0,0,1,0,0,0,0,0,0,0,0
1482531,Little mermaid handmade dress,2,0,Little mermaid handmade dress never worn size 2t,1,0,0,0,1,0,0,0,0,0,0,0,0
1482532,21 day fix containers and eating plan,2,0,"Used once or twice, still in great shape.",0,0,0,0,0,0,0,0,1,0,0,0,0
1482533,World markets lanterns,3,1,There is 2 of each one that you see! So 2 red ...,0,0,0,0,0,0,1,0,0,0,0,0,0
1482534,Brand new lux de ville wallet,1,0,"New with tag, red with sparkle. Firm price, no...",0,0,0,0,1,0,0,0,0,0,0,0,0

In [6]:
y_train

train_id
0          10.0
1          52.0
2          10.0
3          35.0
4          44.0
           ...
1482530    20.0
1482531    14.0
1482532    12.0
1482533    45.0
1482534    22.0
Name: price, Length: 1481661, dtype: float64

In [7]:
test_df

,name,item_condition_id,category_name,brand_name,shipping,item_description
test_id,,,,,,
0,"Breast cancer ""I fight like a girl"" ring",1,Women/Jewelry/Rings,NaN,1,Size 7
1,"25 pcs NEW 7.5""x12"" Kraft Bubble Mailers",1,Other/Office supplies/Shipping Supplies,NaN,1,"25 pcs NEW 7.5""x12"" Kraft Bubble Mailers Lined..."
2,Coach bag,1,Vintage & Collectibles/Bags and Purses/Handbag,Coach,1,Brand new coach bag. Bought for [rm] at a Coac...
3,Floral Kimono,2,Women/Sweaters/Cardigan,NaN,0,-floral kimono -never worn -lightweight and pe...
4,Life after Death,3,Other/Books/Religion & Spirituality,NaN,1,Rediscovering life after the loss of a loved o...
...,...,...,...,...,...,...
693354,Quartz crystal on Flint stone,1,Home/Home Décor/Home Décor Accents,NaN,0,Flint/Quartz cluster. Self mined ✨measures 3x2...
693355,It Cosmetics - Travel Bundle,1,Beauty/Makeup/Makeup Sets,IT Cosmetics,1,It Cosmetics travel bundle. Includes: Brow pow...
693356,Galaxy S8 hard shell case,1,"Electronics/Cell Phones & Accessories/Cases, C...",NaN,1,New. Free shipping Basstop case
693357,Hi low floral kimono,2,Women/Swimwear/Cover-Ups,NaN,0,Floral kimono. Tropical print. Open front. Hi ...
693358,"FREESHIP 2 Floral Scrub Tops, medium.",2,Women/Tops & Blouses/T-Shirts,NaN,1,2 Floral scrub tops. Worn less than 5 times ea...

In [8]:
preprocess(test_df)

,name,item_condition_id,shipping,item_description,has_brand,cat_Cosmetics and Body Care,cat_Digital Services,cat_Electronics,cat_Fashion,cat_Food and Beverage,cat_Furniture and Decor,cat_Health and Wellness,cat_Household Items,cat_Media,cat_Office Equipment,cat_Pet Care,cat_Toys and Hobbies
test_id,,,,,,,,,,,,,,,,,
0,"Breast cancer ""I fight like a girl"" ring",1,1,Size 7,0,0,0,0,1,0,0,0,0,0,0,0,0
1,"25 pcs NEW 7.5""x12"" Kraft Bubble Mailers",1,1,"25 pcs NEW 7.5""x12"" Kraft Bubble Mailers Lined...",0,0,0,0,0,0,0,0,0,0,1,0,0
2,Coach bag,1,1,Brand new coach bag. Bought for [rm] at a Coac...,1,0,0,0,1,0,0,0,0,0,0,0,0
3,Floral Kimono,2,0,-floral kimono -never worn -lightweight and pe...,0,0,0,0,1,0,0,0,0,0,0,0,0
4,Life after Death,3,1,Rediscovering life after the loss of a loved o...,0,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693354,Quartz crystal on Flint stone,1,0,Flint/Quartz cluster. Self mined ✨measures 3x2...,0,0,0,0,0,0,1,0,0,0,0,0,0
693355,It Cosmetics - Travel Bundle,1,1,It Cosmetics travel bundle. Includes: Brow pow...,1,1,0,0,0,0,0,0,0,0,0,0,0
693356,Galaxy S8 hard shell case,1,1,New. Free shipping Basstop case,0,0,0,1,0,0,0,0,0,0,0,0,0
693357,Hi low floral kimono,2,0,Floral kimono. Tropical print. Open front. Hi ...,0,0,0,0,1,0,0,0,0,0,0,0,0
693358,"FREESHIP 2 Floral Scrub Tops, medium.",2,1,2 Floral scrub tops. Worn less than 5 times ea...,0,0,0,0,1,0,0,0,0,0,0,0,0