In [1]:
from utils import *

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\danie\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\danie\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package product_reviews_2 to
[nltk_data]     C:\Users\danie\AppData\Roaming\nltk_data...
[nltk_data]   Package product_reviews_2 is already up-to-date!

In [2]:
train_df_orig = load_dataset('local', 'train.tsv')
train_df = train_df_orig

test_df_orig = load_dataset('local', 'test.tsv')
test_df = test_df_orig

# test2_df_orig = load_dataset('local', 'test_stg2.tsv')
# test2_df = test2_df_orig

In [3]:
train_df

,name,item_condition_id,category_name,brand_name,price,shipping,item_description
train_id,,,,,,,
0,MLB Cincinnati Reds T Shirt Size XL,3,Men/Tops/T-shirts,NaN,10.0,1,No description yet
1,Razer BlackWidow Chroma Keyboard,3,Electronics/Computers & Tablets/Components & P...,Razer,52.0,0,This keyboard is in great condition and works ...
2,AVA-VIV Blouse,1,Women/Tops & Blouses/Blouse,Target,10.0,1,Adorable top with a hint of lace and a key hol...
3,Leather Horse Statues,1,Home/Home Décor/Home Décor Accents,NaN,35.0,1,New with tags. Leather horses. Retail for [rm]...
4,24K GOLD plated rose,1,Women/Jewelry/Necklaces,NaN,44.0,0,Complete with certificate of authenticity
...,...,...,...,...,...,...,...
1482530,Free People Inspired Dress,2,Women/Dresses/Mid-Calf,Free People,20.0,1,"Lace, says size small but fits medium perfectl..."
1482531,Little mermaid handmade dress,2,Kids/Girls 2T-5T/Dresses,Disney,14.0,0,Little mermaid handmade dress never worn size 2t
1482532,21 day fix containers and eating plan,2,Sports & Outdoors/Exercise/Fitness accessories,NaN,12.0,0,"Used once or twice, still in great shape."
1482533,World markets lanterns,3,Home/Home Décor/Home Décor Accents,NaN,45.0,1,There is 2 of each one that you see! So 2 red ...
1482534,Brand new lux de ville wallet,1,Women/Women's Accessories/Wallets,NaN,22.0,0,"New with tag, red with sparkle. Firm price, no..."

In [4]:
train_df = preprocess(train_df)
train_df.to_csv('train_pp2.csv')
X_train, y_train = extract_from_trainset(train_df)

In [5]:
X_train

,item_condition_id,shipping,vec0,vec1,vec2,vec3,vec4,vec5,vec6,vec7,...,cat_Electronics,cat_Fashion,cat_Food and Beverage,cat_Furniture and Decor,cat_Health and Wellness,cat_Household Items,cat_Media,cat_Office Equipment,cat_Pet Care,cat_Toys and Hobbies
train_id,,,,,,,,,,,,,,,,,,,,,
0,3,1,-0.007633,0.013877,0.001542,0.002168,-0.002364,-0.014765,0.012060,-0.008765,...,0,1,0,0,0,0,0,0,0,0
1,3,0,0.013427,-0.005142,0.006128,0.001119,-0.010722,0.013957,-0.008687,0.007710,...,1,0,0,0,0,0,0,0,0,0
2,1,1,0.001426,-0.006458,0.002439,0.008610,0.012070,-0.011089,-0.013029,-0.001692,...,0,1,0,0,0,0,0,0,0,0
3,1,1,0.005893,-0.008465,0.012312,-0.003756,0.010533,-0.000997,0.001640,-0.007969,...,0,0,0,1,0,0,0,0,0,0
4,1,0,0.008761,0.012107,-0.013877,-0.008480,-0.004083,-0.001077,-0.014431,0.003161,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1482530,2,1,0.011897,0.014751,0.014285,0.005974,-0.015538,-0.010825,-0.006603,0.013614,...,0,1,0,0,0,0,0,0,0,0
1482531,2,0,-0.005538,0.011826,-0.014858,-0.004269,-0.011221,0.000128,-0.002075,0.001431,...,0,1,0,0,0,0,0,0,0,0
1482532,2,0,-0.004339,-0.001035,-0.013800,-0.014500,-0.010625,-0.014848,0.013021,-0.013314,...,0,0,0,0,0,1,0,0,0,0
1482533,3,1,0.009275,-0.002209,0.007089,0.014941,-0.000295,0.014102,-0.009837,-0.003777,...,0,0,0,1,0,0,0,0,0,0
1482534,1,0,0.001947,-0.009048,0.009350,-0.005333,-0.008319,0.006095,0.003712,-0.001768,...,0,1,0,0,0,0,0,0,0,0

In [6]:
y_train

train_id
0          10.0
1          52.0
2          10.0
3          35.0
4          44.0
           ...
1482530    20.0
1482531    14.0
1482532    12.0
1482533    45.0
1482534    22.0
Name: price, Length: 1481661, dtype: float64

In [7]:
test_df

,name,item_condition_id,category_name,brand_name,shipping,item_description
test_id,,,,,,
0,"Breast cancer ""I fight like a girl"" ring",1,Women/Jewelry/Rings,NaN,1,Size 7
1,"25 pcs NEW 7.5""x12"" Kraft Bubble Mailers",1,Other/Office supplies/Shipping Supplies,NaN,1,"25 pcs NEW 7.5""x12"" Kraft Bubble Mailers Lined..."
2,Coach bag,1,Vintage & Collectibles/Bags and Purses/Handbag,Coach,1,Brand new coach bag. Bought for [rm] at a Coac...
3,Floral Kimono,2,Women/Sweaters/Cardigan,NaN,0,-floral kimono -never worn -lightweight and pe...
4,Life after Death,3,Other/Books/Religion & Spirituality,NaN,1,Rediscovering life after the loss of a loved o...
...,...,...,...,...,...,...
693354,Quartz crystal on Flint stone,1,Home/Home Décor/Home Décor Accents,NaN,0,Flint/Quartz cluster. Self mined ✨measures 3x2...
693355,It Cosmetics - Travel Bundle,1,Beauty/Makeup/Makeup Sets,IT Cosmetics,1,It Cosmetics travel bundle. Includes: Brow pow...
693356,Galaxy S8 hard shell case,1,"Electronics/Cell Phones & Accessories/Cases, C...",NaN,1,New. Free shipping Basstop case
693357,Hi low floral kimono,2,Women/Swimwear/Cover-Ups,NaN,0,Floral kimono. Tropical print. Open front. Hi ...
693358,"FREESHIP 2 Floral Scrub Tops, medium.",2,Women/Tops & Blouses/T-Shirts,NaN,1,2 Floral scrub tops. Worn less than 5 times ea...

In [8]:
test_df = preprocess(test_df)
test_df.to_csv('test_pp2.csv')
test_df

,item_condition_id,shipping,vec0,vec1,vec2,vec3,vec4,vec5,vec6,vec7,...,cat_Electronics,cat_Fashion,cat_Food and Beverage,cat_Furniture and Decor,cat_Health and Wellness,cat_Household Items,cat_Media,cat_Office Equipment,cat_Pet Care,cat_Toys and Hobbies
test_id,,,,,,,,,,,,,,,,,,,,,
0,1,1,-0.009170,-0.012634,-0.006592,-0.006995,-0.006046,-0.006768,0.011584,0.001173,...,0,1,0,0,0,0,0,0,0,0
1,1,1,-0.008170,-0.009984,0.015215,0.007817,0.004612,0.010948,-0.007198,0.004576,...,0,0,0,0,0,0,0,1,0,0
2,1,1,-0.013603,0.008433,-0.014415,0.009674,0.005552,-0.001889,0.006846,0.011518,...,0,1,0,0,0,0,0,0,0,0
3,2,0,0.010091,0.013853,-0.008173,0.011594,-0.013484,0.000744,0.001803,-0.006956,...,0,1,0,0,0,0,0,0,0,0
4,3,1,0.003682,0.008625,0.009014,-0.014524,0.004851,-0.011560,0.001164,-0.006535,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693354,1,0,-0.014980,0.013684,0.005517,-0.003117,0.007499,-0.015458,-0.014831,-0.002818,...,0,0,0,1,0,0,0,0,0,0
693355,1,1,-0.001568,-0.009575,0.005763,0.009205,0.015547,-0.004135,0.014392,-0.005171,...,0,0,0,0,0,0,0,0,0,0
693356,1,1,-0.014832,0.005456,0.010401,-0.008532,0.003531,0.009408,0.005307,0.008305,...,1,0,0,0,0,0,0,0,0,0
693357,2,0,0.009433,0.003937,0.009730,-0.010670,0.010163,0.012626,-0.003105,0.011060,...,0,1,0,0,0,0,0,0,0,0
693358,2,1,-0.006598,-0.005606,-0.012231,0.014159,-0.012769,0.002601,0.015418,-0.013321,...,0,1,0,0,0,0,0,0,0,0